### ISSUE TITLE
Is there a react native sample with both android and ios integrations?

### ISSUE THREAD

**Issue by giantslogik** [acquireio/acquireReactProject#1]
Is there a react native sample with both android and ios integrations? This project seems to have android integrations and not ios.

**Comment by nilayAcquire** [comment]
No, This project has only Android SDK integration.

**Comment by giantslogik** [comment]
Is there some technical blocker for an ios React Native integration? Should i raise an issue on the ios project ?

**Comment by nilayAcquire** [comment]
No there is no technical blocker. Our iOS team is working on this.
